###

POST http://localhost:8080/api/v1/webhook
Content-Type: application/json

{
  "notification_id": 1,
  "organizer": "kvkraichgau",
  "event": "zeltlager23ma",
  "code": "3PCGD",
  "action": "pretix.event.order.approved"
}